### ISSUE TITLE
about plural forms of substantive 

### ISSUE THREAD

**Issue by Hongchao-Zhang-PUMC** [Schluckauf-weg/DeutscheGrammatik.github.io#1]
您好，您对名词词性变化的归纳，实在是帮助很大。但未能理解您的名词变复数的分类方法。如果方便，想请教您参考的语法资料。

另，下附链接给出了12种名词变复数的变形形式，不知道对您是否有参考意义。
http://www.deutschseite.de/grammatik/plural/plural.html

再次感谢。

**Comment by Schluckauf-weg** [comment]
非常高兴这个项目对您有所帮助。这些总结都不是我的原创，在项目前言里面致谢了来源：

> 内容主要引用自肖深刻的九叔（微信公众号：xiao9shu）原创德语学习文章。强烈推荐参加九叔创立的达赫德语学校的课程。
语法专业术语参考《德语语法表解》，华宗德主编。

肖老师的公众号文章对我帮助很大，但是微信的内容碎片化比较严重，不方便查询和复习，所以我把内容按照语法书的方式重新组织，再根据《德语语法表解》补充一点定义和解释。

关于名词变复数，您可以在肖老师的公众号中查询，我这里的摘录有点太简化了。

祝学习愉快！
