### ISSUE TITLE
不规则动词变位a → ä → ie → a中有2个单词不是该规则

### ISSUE THREAD

**Issue by rchqi** [Schluckauf-weg/DeutscheGrammatik.github.io#2]
你好大大，请问这2个单词为什么会被列入这个规则中。以及可以发一下“不规则动词”这个知识点的九叔公众号的链接吗，我在公众号里面搜索“不规则动词”没找到。
![Snipaste_2024-10-19_22-04-16](https://github.com/user-attachments/assets/b8b17d8d-0eea-4bcc-ae2d-d3c37f009cc9)

谢谢！

**Comment by Schluckauf-weg** [comment]
您好，我没有读到过肖老师关于不规则动词的公众号文章。这个分类是我为了方便记忆自己做的。最后两个是形式上有点类似所以也放到一起了。

祝学习愉快！

**Comment by rchqi** [comment]
好的，谢谢大佬，这个网站好棒
